name: automated tests

trigger:
  branches:
    include:
      - main

jobs:
- job: run_tests
  displayName: Run automated tests
  pool:
    vmImage: 'macOS-latest'
  
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm i --save-dev cypress-mochawesome-reporter
    displayName: 'Install Mochawesome dependencies for reporting'

  - script: npm run test
    displayName: 'Run automated tests'
